# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ToDoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToDoApp
  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  pod 'RealmSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'FSCalendar'
  pod 'CalculateCalendarLogic'
  pod 'DZNEmptyDataSet'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end